### ISSUE TITLE
small bug in use of defusr/usr

### ISSUE THREAD

**Issue by wilsonpilon** [farique1/basic-dignified#2]
Hi Rique.

Compiling this small routine:

	color 15,1,1:
	screen 2:
	screen 1:
	defusr=&h7e:
	x=usr(0)

in MSX extension results:
7color15,1,1:screen2:screen1:zz=&h7e:x=zy(0)

using defusr0, works fine, maybe a note warning about the need to use 0 after defusr

**Comment by farique1** [comment]
I'll take a look at that and if it is not too complicated I'll fix it before reuploading the other changes.
I think I just have to update the regex dealing with "defusr" and "usr" to accept them as keywords without a trailing number.
If I can't fix it right now I'll add the warning.
Thanks.

**Comment by farique1** [comment]
Ok, that was it. Managed to make your example work, also tested with a trailing number just in case.
Changed r'DEFUSR\d' to r'DEFUSR(\d)?'. Same thing with USR.

**Comment by wilsonpilon** [comment]
Wonderful. I changed badig_msx.py here and it worked. 

Gee, I should have opened the source earlier, even not knowing much Python the program is well commented. Next time I'll look at the source first to report more details. Thanks!

**Comment by farique1** [comment]
Please, mess with the code, that is why there are so many comments (this and my fleeting memory) (and still a lot of commenting to do on the newer stuff). The more people know the program the more we can improve the thing.
BUT, remember to always report back the bugs and issues so we can all benefit from it.
Thanks again.
I will close this and the other issue, but do get in touch for any report, comments or even requests you might have.
Cheers!
