### ISSUE TITLE
Problem Interpreting the EOF() Function in MSX-BASIC

### ISSUE THREAD

**Issue by wilsonpilon** [farique1/basic-dignified#3]
Hello Rique, I noticed a small problem in this function

When I try to pass this code to badig:
```
open "main.bin" as #1 len=1
field #1,1 as a$
registro=1
if eof(1) then _ 
	goto {fim} 
else 
	get #1,registro:
	print hex$(asc(a$));:
	registro++:
	goto {@}
{fim}
close #1
end
```

The resulting program looks like this:
```
1'Converted with Basic Dignified
2'https://github.com/farique1/basic-dignified
3open"main.bin"as#1len=1
4field#1,1 asa$
5zz=1
```
looks like it stops when finding a line with EOF()

Searching the source code, I noticed that you use EOF in BADIG itself
```
badig.py:
 # General groups
        m_eof = r'^EOF$'
        m_newline = r'^\r+$'
        m_spaces = r'^[^\S\r\n]$'
```
Again, congratulations on the great work with these tools. Cheers!

**Comment by farique1** [comment]
Yeah, that is it, I'm adding an "EOF" string to the end of the loaded file and that regex you saw is responsible for recognizing it as the last line.

There are two problems there:
1. I should't be adding that line on the generic load function.
2. I shouldn't be using a string, let alone one with valid characters.

I will fix this as soon as I can.
Thanks for the report!

**Comment by farique1** [comment]
Hi Pilon,
Took me some time but I figured out a way to fix both issues.
The EOF token is now added based on the last line of the code and not on a arbitrary text added at the end.

Would you like to test the fixed files?
(helper.py is on the "support" folder)
[NewFiles.zip](https://github.com/farique1/basic-dignified/files/11337370/NewFiles.zip)

Cheers!

**Comment by farique1** [comment]
Hi Pilon,
Took me some time but I figured out a way to fix both issues.
The EOF token is now added based on the last line of the code and not on a arbitrary text added at the end.

Would you like to test the fixed files?
(helper.py is on the "support" folder)
[NewFiles.zip](https://github.com/farique1/basic-dignified/files/11337610/NewFiles.zip)

Cheers!

**Comment by wilsonpilon** [comment]
Hi Rique.

I ran the test on that example and a few others, and everything worked fine.

Thank you very much!

**Comment by farique1** [comment]
Cool!
The solution is still a bit jerry rigged but I'll update the repo.
Keep the bugs coming 😆
